export const GET_ITEMS_REQUEST = 'GET_ITEMS_REQUEST';
export const GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS';
export const GET_ITEMS_FAILURE = 'GET_ITEMS_FAILURE';

export const SELECT_ITEM = 'SELECT_ITEM';

export const UPDATE_PERSON_REQUEST = 'UPDATE_PERSON_REQUEST';
export const UPDATE_PERSON_SUCCESS = 'UPDATE_PERSON_SUCCESS';
export const UPDATE_PERSON_FAILURE = 'UPDATE_PERSON_FAILURE';

export const UPDATE_GROUP_REQUEST = 'UPDATE_GROUP_REQUEST';
export const UPDATE_GROUP_SUCCESS = 'UPDATE_GROUP_SUCCESS';
export const UPDATE_GROUP_FAILURE = 'UPDATE_GROUP_FAILURE';

export const MESSAGE_PERSON_REQUEST = 'MESSAGE_PERSON_REQUEST';
export const MESSAGE_PERSON_SUCCESS = 'MESSAGE_PERSON_SUCCESS';
export const MESSAGE_PERSON_FAILURE = 'MESSAGE_PERSON_FAILURE';

export const MESSAGE_GROUP_REQUEST = 'MESSAGE_GROUP_REQUEST';
export const MESSAGE_GROUP_SUCCESS = 'MESSAGE_GROUP_SUCCESS';
export const MESSAGE_GROUP_FAILURE = 'MESSAGE_GROUP_FAILURE';

export const  UPLOAD_IMAGE_REQUEST = 'UPLOAD_IMAGE_REQUEST';
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS';
export const UPLOAD_IMAGE_FAILURE = 'UPLOAD_IMAGE_FAILURE';
