export const GET_ITEMS_REQUEST = 'GET_ITEMS_REQUEST';
export const GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS';
export const GET_ITEMS_FAILURE = 'GET_ITEMS_FAILURE';

export const SELECT_ITEM = 'SELECT_ITEM';

export const UPDATE_PERSON_REQUEST = 'UPDATE_PERSON_REQUEST';
export const UPDATE_PERSON_SUCCESS = 'UPDATE_PERSON_SUCCESS';
export const UPDATE_PERSON_FAILURE = 'UPDATE_PERSON_FAILURE';

export const UPDATE_GROUP_REQUEST = 'UPDATE_GROUP_REQUEST';
export const UPDATE_GROUP_SUCCESS = 'UPDATE_GROUP_SUCCESS';
export const UPDATE_GROUP_FAILURE = 'UPDATE_GROUP_FAILURE';

export const MESSAGE_PERSON_REQUEST = 'MESSAGE_PERSON_REQUEST';
export const MESSAGE_PERSON_SUCCESS = 'MESSAGE_PERSON_SUCCESS';
export const MESSAGE_PERSON_FAILURE = 'MESSAGE_PERSON_FAILURE';

export const MESSAGE_GROUP_REQUEST = 'MESSAGE_GROUP_REQUEST';
export const MESSAGE_GROUP_SUCCESS = 'MESSAGE_GROUP_SUCCESS';
export const MESSAGE_GROUP_FAILURE = 'MESSAGE_GROUP_FAILURE';

export const UPLOAD_IMAGE_REQUEST = 'UPLOAD_IMAGE_REQUEST';
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS';
export const UPLOAD_IMAGE_FAILURE = 'UPLOAD_IMAGE_FAILURE';

export const RESET_POPUP_STATE = 'RESET_POPUP_STATE';


export const DELETE_GROUP_REQUEST = 'DELETE_GROUP_REQUEST';
export const DELETE_GROUP_SUCCESS = 'DELETE_GROUP_SUCCESS';
export const DELETE_GROUP_FAILURE = 'DELETE_GROUP_FAILURE';

export const DELETE_PERSON_REQUEST = 'DELETE_PERSON_REQUEST';
export const DELETE_PERSON_SUCCESS = 'DELETE_PERSON_SUCCESS';
export const DELETE_PERSON_FAILURE = 'DELETE_PERSON_FAILURE';

export const ADD_GROUP_REQUEST = 'ADD_GROUP_REQUEST';
export const ADD_GROUP_SUCCESS = 'ADD_GROUP_SUCCESS';
export const ADD_GROUP_FAILURE = 'ADD_GROUP_FAILURE';

export const ADD_PERSON_REQUEST = 'ADD_PERSON_REQUEST';
export const ADD_PERSON_SUCCESS = 'ADD_PERSON_SUCCESS';
export const ADD_PERSON_FAILURE = 'ADD_PERSON_FAILURE';

export const REFRESH_ITEMS_REQUEST = 'REFRESH_ITEMS_REQUEST';
export const REFRESH_ITEMS_SUCCESS = 'REFRESH_ITEMS_SUCCESS';
export const REFRESH_ITEMS_FAILURE = 'REFRESH_ITEMS_FAILURE';

export const GO_BACK = 'GO_BACK';

export const SEARCH_ITEMS = 'SEARCH_ITEMS';
export const SEARCH_PEOPLE = 'SEARCH_PEOPLE';
export const SEARCH_GROUPS = 'SEARCH_GROUPS';

export const RESET_SEARCH_RESULTS = 'RESET_SEARCH_RESULTS';

export const ADD_PERSON_TO_GROUP_REQUEST = 'ADD_PERSON_TO_GROUP_REQUEST';
export const ADD_PERSON_TO_GROUP_SUCCESS = 'ADD_PERSON_TO_GROUP_SUCCESS';
export const ADD_PERSON_TO_GROUP_FAILURE = 'ADD_PERSON_TO_GROUP_FAILURE';

export const SELECT_GROUP = 'SELECT_GROUP';

export const RELATE_GUARDIAN_TO_PERSON_REQUEST = 'RELATE_GUARDIAN_TO_PERSON_REQUEST';
export const RELATE_GUARDIAN_TO_PERSON_SUCCESS = 'RELATE_GUARDIAN_TO_PERSON_SUCCESS';
export const RELATE_GUARDIAN_TO_PERSON_FAILURE = 'RELATE_GUARDIAN_TO_PERSON_FAILURE';






