export const RELATE_GUARDIAN_TO_PERSON_REQUEST = 'RELATE_GUARDIAN_TO_PERSON_REQUEST';
export const RELATE_GUARDIAN_TO_PERSON_SUCCESS = 'RELATE_GUARDIAN_TO_PERSON_SUCCESS';
export const RELATE_GUARDIAN_TO_PERSON_FAILURE = 'RELATE_GUARDIAN_TO_PERSON_FAILURE';

export const ADD_GUARDIAN_REQUEST = 'ADD_GUARDIAN_REQUEST';
export const ADD_GUARDIAN_SUCCESS = 'ADD_GUARDIAN_SUCCESS';
export const ADD_GUARDIAN_FAILURE = 'ADD_GUARDIAN_FAILURE';
