export const ADD_PERSON_TO_GROUP_REQUEST = 'ADD_PERSON_TO_GROUP_REQUEST';
export const ADD_PERSON_TO_GROUP_SUCCESS = 'ADD_PERSON_TO_GROUP_SUCCESS';
export const ADD_PERSON_TO_GROUP_FAILURE = 'ADD_PERSON_TO_GROUP_FAILURE';
