export const GET_ITEMS_REQUEST = 'GET_ITEMS_REQUEST';
export const GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS';
export const GET_ITEMS_FAILURE = 'GET_ITEMS_FAILURE';

export const SELECT_ITEM = 'SELECT_ITEM';

export const REFRESH_ITEMS_REQUEST = 'REFRESH_ITEMS_REQUEST';
export const REFRESH_ITEMS_SUCCESS = 'REFRESH_ITEMS_SUCCESS';
export const REFRESH_ITEMS_FAILURE = 'REFRESH_ITEMS_FAILURE';
