export const SUBMIT_PHONE_FOR_LOGIN_REQUEST = 'SUBMIT_PHONE_FOR_LOGIN_REQUEST';
export const SUBMIT_PHONE_FOR_LOGIN_SUCCESS = 'SUBMIT_PHONE_FOR_LOGIN_SUCCESS';
export const SUBMIT_PHONE_FOR_LOGIN_FAILURE = 'SUBMIT_PHONE_FOR_LOGIN_FAILURE';

export const SUBMIT_CODE_FOR_LOGIN_REQUEST = 'SUBMIT_CODE_FOR_LOGIN_REQUEST';
export const SUBMIT_CODE_FOR_LOGIN_SUCCESS = 'SUBMIT_CODE_FOR_LOGIN_SUCCESS';
export const SUBMIT_CODE_FOR_LOGIN_FAILURE = 'SUBMIT_CODE_FOR_LOGIN_FAILURE';

export const REINIT_LOGIN = 'REINIT_LOGIN';
export const SET_SESSION_CODE_SUCCESS = 'SET_SESSION_CODE_SUCCESS';
