export const RELATE_GUARDIAN_TO_PERSON_REQUEST = 'RELATE_GUARDIAN_TO_PERSON_REQUEST';
export const RELATE_GUARDIAN_TO_PERSON_SUCCESS = 'RELATE_GUARDIAN_TO_PERSON_SUCCESS';
export const RELATE_GUARDIAN_TO_PERSON_FAILURE = 'RELATE_GUARDIAN_TO_PERSON_FAILURE';
