export const UNLINK_PERSON_FROM_GROUP_REQUEST = 'UNLINK_PERSON_FROM_GROUP_REQUEST';
export const UNLINK_PERSON_FROM_GROUP_SUCCESS = 'UNLINK_PERSON_FROM_GROUP_SUCCESS';
export const UNLINK_PERSON_FROM_GROUP_FAILURE = 'UNLINK_PERSON_FROM_GROUP_FAILURE';
